### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by VictorLeeLk** [dennybritz/reinforcement-learning#173]
Hello,when I run the dqn.py ,I got this problem,how can I solve it?  more information as follows:
`Step 837 (5812168) @ Episode 2147/10000, loss: 0.0055155428126454353
Episode Reward: 12.0
Step 921 (5813089) @ Episode 2148/10000, loss: 0.0395831167697906595
Episode Reward: 16.0
Step 779 (5813868) @ Episode 2149/10000, loss: 0.0024324192199856043
Episode Reward: 13.0
Step 785 (5814653) @ Episode 2150/10000, loss: 0.0053424858488142495
Episode Reward: 14.0
Traceback (most recent call last):
  File "dqn.py", line 445, in <module>
    batch_size=32):
  File "dqn.py", line 335, in deep_q_learning
    state = env.reset()
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitor.py", line 39, in reset
    self._after_reset(observation)
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitor.py", line 193, in _after_reset
    self.reset_video_recorder()
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitor.py", line 214, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitoring/video_recorder.py", line 116, in capture_frame
    self._encode_image_frame(frame)
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitoring/video_recorder.py", line 162, in _encode_image_frame
    self.encoder = ImageEncoder(self.path, frame.shape, self.frames_per_sec)
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitoring/video_recorder.py", line 256, in __init__
    self.start()
  File "/home/victorleelk/MyPro/gym/gym/wrappers/monitoring/video_recorder.py", line 288, in start
    self.proc = subprocess.Popen(self.cmdline, stdin=subprocess.PIPE, preexec_fn=os.setsid)
  File "/home/victorleelk/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/victorleelk/anaconda3/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
`
My hardware and software as follows:
ubuntu16.04LTS
RAM:32G
tensorflow-gpu:1.10.0
gym:0.10.5

Help,Thanks!

**Comment by Brisingr-thu** [comment]
I think this error occurs due to the replay memory which is allocate on the memory. The whole replay memory would be too large though for memory the os had used some virtual memory. Actually I am also facing this problem. There are two solutions I am now trying: using numpy.memmap or using h5py library. These two solutions both aim to store the huge numpy array list into the disk (but at the same time this would slow down the running speed)

**Comment by z-huabao** [comment]
this solve it: https://github.com/openai/gym/issues/110
