### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'partition_info' in Continuous MountainCar Actor Critic Solution.ipynb 

### ISSUE THREAD

**Issue by IvanKush** [dennybritz/reinforcement-learning#88]
get subj error

**Continuous MountainCar Actor Critic Solution.ipynb**

python-3.5.2
tensorflow '1.0.0'

```
policy_estimator = PolicyEstimator(learning_rate=0.001)
Traceback (most recent call last):

  File "<ipython-input-11-43279115f702>", line 1, in <module>
    policy_estimator = PolicyEstimator(learning_rate=0.001)

  File "<ipython-input-5-f8a13258f23d>", line 17, in __init__
    weights_initializer=tf.zeros_initializer)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1409, in fully_connected
    outputs = layer.apply(inputs)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 269, in __call__
    self.build(input_shapes[0])

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\layers\core.py", line 123, in build
    trainable=True)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 341, in get_variable
    validate_shape=validate_shape)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 258, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 208, in _add_variable
    trainable=trainable and self.trainable)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1310, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1299, in _model_variable_getter
    custom_getter=getter)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 268, in model_variable
    partitioner=partitioner, custom_getter=custom_getter)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 225, in variable
    partitioner=partitioner)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variables.py", line 226, in __init__
    expected_shape=expected_shape)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)

  File "D:\soft\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)

TypeError: __init__() got an unexpected keyword argument 'partition_info'
```

**Comment by cosmmb** [comment]
I have the same issue too.
